version: "3"
services:
  # mongozexe:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   ports:
  #     - 27027:27017
  #   volumes:
  #     - ./data/dump:/dump
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  # Scorer Node
  api:
    # image: mubashirzebi/zexe-arbitrum-2.0:latest
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - mongozexe
    ports:
      - "4020:3010"
    environment:
        - NODE_ENV=stage
        # - MONGO_URL=mongodb+srv://g-2-project-1:AzVr1gDMWsMc1lAN@cluster0.j1yrl.mongodb.net/prod
        - MONGO_URL=mongodb+srv://g-2-project-1:AzVr1gDMWsMc1lAN@cluster0.j1yrl.mongodb.net/dev
        - PRIVATE_KEY1=0x7cf03fae45cb10d4e3ba00a10deeacfc8cea1be0eebcfb7277a7df2e5074a405
        
  #     - PORT=${PORT}
  #     - ANALYSER_PORT=${ANALYSER_PORT}
  #     - ANALYSER_SERVER_STRING=analyser
  #     - COVALENT_API=${COVALENT_API}
  #     - MONGO_USER=${MONGO_USER}
  #     - MONGO_PWD=${MONGO_PWD}
  #     - MONGO_PORT=${MONGO_PORT}
  #     - DB_SERVER_STRING=mongo
  #     - DB_NAME=${DB_NAME}
  #     - TOKENS_COLLECTION_NAME=${TOKENS_COLLECTION_NAME}
  #     - SYNCS_COLLECTION_NAME=${SYNCS_COLLECTION_NAME}
  #     - HOLDINGS_COLLECTION_NAME=${HOLDINGS_COLLECTION_NAME}
  #     - CREDIT_COLLECTION_NAME=${CREDIT_COLLECTION_NAME}
  #     - MASTER_API_KEY=${MASTER_API_KEY}
    command: npm run dev
             
